### PR TITLE
Fixes attachment issues

### PR DESCRIPTION
**Pull request by Scullyy**
**Describe Pull request**
This will fix issues with attachments not popping up in the attachment window, attachment images not showing in the attachment window and attachments not removing when being dragged to the remove button.

**Questions:**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by jaylac2000 — APPROVED** [review]

**Comment by TonybynMp4** [comment]
it doesn't seem to work, 
it gives me the following errors
image
image
and if i comment the line 106 and try and remove an attachment it gives that error
image
image

**Comment by Scullyy** [comment]
> it doesn't seem to work,
> it gives me the following errors
> image
> image
> and if i comment the line 106 and try and remove an attachment it gives that error
> image
> image

You must have made the changes incorrectly, download it from my GitHub. I already pushed the fix to my qb-inventory and also LJ-inventory. It’s been tested on lj-inventory and pushed to the main repo by their maintainers too.

**Comment by TonybynMp4** [comment]
> You must have made the changes incorrectly, download it from my GitHub. I already pushed the fix to my qb-inventory and also LJ-inventory. It’s been tested on lj-inventory and pushed to the main repo by their maintainers too.

downloaded your repo and it still does the same thing

**Comment by TonybynMp4** [comment]
@Scullyy i tested it again and it seems it gives the error when the weapon comes pre equiped with attachements from the police armory

**Review by TonybynMp4 — APPROVED** [review]
the policejobs config needs an update but this works fine for the other weapons!

**Comment by Aries-RSPS** [comment]
this works however the inventory doesnt update when u take off the attachment is there a way to force it to update?

**Comment by nzkfc** [comment]
> **Describe Pull request** This will fix issues with attachments not popping up in the attachment window, attachment images not showing in the attachment window and attachments not removing when being dragged to the remove button.
> 
> **Questions:**
> 
>     * Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
> 
>     * Does your code fit the style guidelines? [yes]
> 
>     * Does your PR fit the contribution guidelines? [yes]

Not that this PR was used, but I see attachment have broken again in latest update too, so we may need your skills again ;)

**Pull request closed without merging**
