### PR TITLE
Add per-vehicle customizable trunk size

### PR DESCRIPTION
**Pull request by TonybynMp4**
**Describe Pull request**
**Requires PR in QB-core ( https://github.com/qbcore-framework/qb-core/pull/707 )**
Allows the customization of the trunk size in the Shared/vehicles.lua

#278 
https://github.com/qbcore-framework/qb-core/issues/680

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by nullvariable** [comment]
I'm in favor of this change, and looks good so far. I would like to see the default slots/weight values moved into the config file so that folks can modify those to their liking.

I would also prefer to have an on/off for this so that people who wish to use the same value across all vehicles as it's set now can continue to use it that way.

**Comment by TonybynMp4** [comment]
I'll see if i can do that

**Review by FjamZoo — CHANGES_REQUESTED** [review]
Change 

`if QBCore.Shared.Vehicles[vehname] ~= nil then` to `if QBCore.Shared.Vehicles[vehname] then`
We tend not to use ~= nil as we can just check if theres a value.

**Comment by Lionh34rt** [comment]
Should make use of vehicle hash probably,

````
local hash = GetEntityModel(curVeh)
local maxweight = 100000 -- default
local slots = 30 -- default, can be a config thing i guess

if QBCore.Shared.VehicleHashes[hash] then
   maxweight = QBCore.Shared.VehicleHashes[hash].maxweight
  slots = QBCore.Shared.VehicleHashes[hash].slots
end
```

**Comment by Lionh34rt** [comment]
> i have this error @lj-inventory/client/main.lua:84: attempt to index a nil value (field 'VehicleHashes')^7 what i'm doing wrong?

That you're using a qb-core version that is not up to date to test new features

**Comment by Vengeance977** [comment]
i changed my qb-core seems working now....but that unconfigured trunk weight/slot not really works,on unconfigured cars i have 60kg weight trunk.

**Comment by TonybynMp4** [comment]
> i changed my qb-core seems working now....but that unconfigured trunk weight/slot not really works,on unconfigured cars i have 60kg weight trunk.

something must be wrong on your side, i removed a car from the vehicles.lua and it's at 10kg not 60

**Comment by Vengeance977** [comment]
> > i changed my qb-core seems working now....but that unconfigured trunk weight/slot not really works,on unconfigured cars i have 60kg weight trunk.
> 
> something must be wrong on your side, i removed a car from the vehicles.lua and it's at 10kg not 60




works great ... i thought that default weight / slot config works that way when i don't do on vehicles.lua ['maxweight'] - ['slot'].
but i tested on a car which isn't in that list and works fine.

**Pull request closed without merging**
