### PR TITLE
giveitem and cancarryitem

### PR DESCRIPTION
**Pull request by i-kulgu**
## Description

With this PR you can give an item more controlled.
You'll get a list of nearby players and when you choose a player it will give the item to that selected player.

Preview:
https://www.youtube.com/watch?v=WtpmP7GfGF0

Also added an export to check if the user can carry an amount of item.
Usage : 

```lua
local cancarry = exports['qb-inventory']:CanCarryItem(src,item,amount)
if not cancarry then TriggerClientEvent("QBCore:Notify", src, "Not enough room in inventory", "error") return end
```

## Checklist

- [X ] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [X ] My code fits the style guidelines.
- [X ] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by QBLes** [comment]
i can Confirm this works.

**Review by Doxria — APPROVED** [review]
LGTM

**Comment by xxUnknown13xx** [comment]
Where can I add this? :) ```local cancarry = exports['qb-inventory']:CanCarryItem(src,item,amount)
if not cancarry then TriggerClientEvent("QBCore:Notify", src, "Not enough room in inventory", "error") return end```

**Comment by i-kulgu** [comment]
> Where can I add this? :) `local cancarry = exports['qb-inventory']:CanCarryItem(src,item,amount) if not cancarry then TriggerClientEvent("QBCore:Notify", src, "Not enough room in inventory", "error") return end`

Inside any script where you want to check if the user can carry an item before giving it.
Export will return a boolean so you can use that also in an if statement like :

```lua
local cancarry = exports['qb-inventory']:CanCarryItem(src,item,amount)
if cancarry then
    print('You can carry this item')
    -- User can carry the given item with given amount
else
    print('You can\'t carry this item')
    -- User can't carry the given item with given amount
end
```

**Comment by i-kulgu** [comment]
> player name appears duplicate

See the latest commit, it's fixed in there

**Pull request closed without merging**
