### PR TITLE
Rework of logic parts (lua)

### PR DESCRIPTION
**Pull request by restray**
## 🎒 A brand new code

The inventory begins to get old with all the releases that the qb-core had.
The players, server owners and qb-team need this script to be updated on last QB functionalities to let the final user enjoy a secure, light and easy-to-use script.

### 🎯 Goals

- Refactor the whole server + client lua part
- Add real-time computed functions (for weight, inventory lock, etc...)
- Optimize the server loops
- Optimize the client menus/inventory usage

### ✅ ToDo list

WIP

 - [ ] Make a PR for police job (instead of small-resources)

### CODE REVIEW

**Comment by xenfovn** [comment]
Can you fix the infinite fuel can?

**Comment by restray** [comment]
> Can you fix the infinite fuel can?

You are talking about the #90 PR!

**Comment by ItsANoBrainer** [comment]
> Can you fix the infinite fuel can?

@xenfovn Keep comments relevant to the pull request.

**Comment by trclassic92** [comment]
https://youtu.be/gqppJLjZ0Q8

**Pull request closed without merging**
