### PR TITLE
allow - in stash names

### PR DESCRIPTION
**Pull request by loaf-scripts**

### CODE REVIEW

**Review by YeahItsHayden — APPROVED** [review]

**Comment by restray** [comment]
Can you please explain to us why, how, to who, etc...

Leaving an empty description is never helpful, it's maybe useful to you, but it's to us ?

I'm reviewing your changes rn!

**Comment by loaf-scripts** [comment]
> Can you please explain to us why, how, to who, etc...
> 
> Leaving an empty description is never helpful, it's maybe useful to you, but it's to us ?
> 
> I'm reviewing your changes rn!

not sure why a description is needed, the title explains the changes "allow - in stash names", i just changed the way the script splits the inventory name from the stash type so you can use a dash in the name without the inventory breaking

**Review by restray — CHANGES_REQUESTED** [review]
A non important feature, the code is not explicit and is not bug proof.

Test with a stash named: `police-stash-test`, it should be buggy. I recommend you to use a `:sub` instead of `:gsub` as the inventory type is fixed to the beginning of the inventory name.

**Comment by loaf-scripts** [comment]
true, i will update the code when i get home & pr

**Pull request closed without merging**
