### PR TITLE
Fixed conflict with the names of some stashes.

### PR DESCRIPTION
**Pull request by hakos47**
## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Review by Qwerty1Verified — CHANGES_REQUESTED** [review]
`-` is a special character with pattern matching and should be escaped using `%`. I can't think of an example currently other than something like `stash-animalshop` which would match 'sho' at the end of the string and isn't the desired behaviour.

I'd stick to find though since it's a quicker function and there's no reason to switch to match. Perhaps there's a reason you switched to match?

**Comment by hakos47** [comment]
"The reason I used match is that I'm more accustomed to using it in these types of situations. However, I agree that find is faster and more efficient for this specific case. It can definitely be done with find as well—it's just a matter of preference for now.

**Comment by GhzGarage** [comment]
Do you have some example of this actually doing anything? Technically it shouldn't

**Comment by Qwerty1Verified** [comment]
@GhzGarage take a look at the example I used, I imagine theirs is similar. Their example could provide some insight too.

**Comment by hakos47** [comment]
When creating a stash with burgershoot it recognizes it as a store

**Review by Qwerty1Verified — APPROVED** [review]

**Pull request merged**
