### PR TITLE
Optimize, cleanup and fix drop issue

### PR DESCRIPTION
**Pull request by BerkieBb**
The drop issue is that if you drop 2 items as close as you can next to each other, one of the items will disappear in an inventory that stays in open state in the script

### CODE REVIEW

**Comment by evanillaa** [comment]
download to try

**Review by evanillaa — APPROVED** [review]
special suggestion

**Comment by evanillaa** [comment]
@BerkieBb conflicts im sad

**Comment by BerkieBb** [comment]
I'll fix the conflicts when I get back from vacation

**Comment by BerkieBb** [comment]
Fixed the conflicts

**Comment by FaultyMatrix** [comment]
If you still drop two items as close as you can to each other, you cant access the first drop without first emptying the second drop by picking it up. Opening the inventory while standing on the first drop either opens a stash-none, or opens the second drop only.

**Comment by BerkieBb** [comment]
This fix prevents the first one from completely disappearing even if you removed the second one, it would always open a stash-none on the first drop

**Comment by BerkieBb** [comment]
So what you experienced is the expected outcome as of now

**Comment by evanillaa** [comment]
I hope this amendment will be approved before a new conflicts appears

**Comment by BerkieBb** [comment]
Fixed conflics again

**Comment by evanillaa** [comment]
can approve this ?
@GhzGarage

**Review by evanillaa — APPROVED** [review]

**Pull request merged**
