### PR TITLE
fix(server): save usable items to qb-core

### PR DESCRIPTION
**Pull request by BerkieBb**
**Describe Pull request**
This fixes the deletion of the usable items whenever you restart qb-inventory, this PR is together with https://github.com/qbcore-framework/qb-core/pull/798

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by 19adorest** [comment]
Screenshot_10
still facing the same problem when we try to use item from hotbar, double click or drag to use

**Comment by BerkieBb** [comment]
If I just read the code, you shouldn't be able to get that error, are you sure you updated correctly?

**Comment by 19adorest** [comment]
> 

Screenshot_17
Yes sir, i did exactly the same as your PR.

**Comment by BerkieBb** [comment]
And your qb-core is updated as well?

**Comment by 19adorest** [comment]
> And your qb-core is updated as well?

Yes sir, i just install all fresh qb-core resources yesterday & i do update this one too [https://github.com/qbcore-framework/qb-core/pull/798](https://github.com/qbcore-framework/qb-core/pull/798)

**Comment by BerkieBb** [comment]
I'll test it later today again and see if I have a fix then

**Comment by BerkieBb** [comment]
> > And your qb-core is updated as well?
> 
> Yes sir, i just install all fresh qb-core resources yesterday & i do update this one too [qbcore-framework/qb-core#798](https://github.com/qbcore-framework/qb-core/pull/798)

Fixed it now

**Pull request merged**
