### PR TITLE
Give Button & Events

### PR DESCRIPTION
**Pull request by Demo4889**
This is a PR which includes both PR #97 and PR #96 , and includes both the HTML and JS sides as well which are functional and Tested. The only testing that needs to be done is updating the players inventory after the giving is complete. Otherwise it is working flawlessly

### CODE REVIEW

**Comment by Demo4889** [comment]
Currently only seems to work with non-weapon items. still testing the weapon giving

**Review by zfbx — APPROVED** [review]
Looks good if feature is desired

**Comment by evanillaa** [comment]
nice addon thank you

**Comment by evanillaa** [comment]
Tested on a server with a group of friends
The results were good

**Review by evanillaa — APPROVED** [review]

**Pull request closed without merging**
