### PR TITLE
More Vending Machines (V2)

### PR DESCRIPTION
**Pull request by S4pphiree**
Added more vending machine types:

- Water Dispenser
- Coffee Machine
- Snack Machine

I used a method like the one for the Delete Laser in qb-adminmenu, tested it and everything works like it should. Now there's no problem when you're near two or more vending machines

Update: Also works with qb-target!

### CODE REVIEW

**Comment by TonybynMp4** [comment]
please update it 🥺

**Comment by TonybynMp4** [comment]
image

**Comment by S4pphiree** [comment]
> image

Whooops I forgot to add an end)

**Comment by TonybynMp4** [comment]
now it's perfect and ready to be merged 👍

**Comment by TonybynMp4** [comment]
image
Would you know how to fix this ?
It seems like if i try to open the inventory near a prop that isn't a vending machine it does that and doesn't open the inventory, and it can cause problems in some interiors like fleeca banks where space is limited with props almost everywhere.

**Comment by S4pphiree** [comment]
> image Would you know how to fix this ? It seems like if i try to open the inventory near a prop that isn't a vending machine it does that and doesn't open the inventory, and it can cause problems in some interiors like fleeca banks where space is limited with props almost everywhere.

I'm working on it

**Comment by DannysRP** [comment]
Still working on this?

**Comment by S4pphiree** [comment]
> Still working on this?

I fixed it, kinda in a janky way, but it works

**Comment by S4pphiree** [comment]
What I've done is "pretty simple", I've got the results from the FindObjectFromRayCast() function and just got every result from every vending machine, I hope it helps

**Comment by S4pphiree** [comment]
Ok it doesn't work, give me some time to think about it

**Comment by S4pphiree** [comment]
I'm done, everything works just fine

**Review by TonybynMp4 — APPROVED** [review]

**Comment by erikmeyer08** [comment]
Is this ready to be merged?

**Comment by S4pphiree** [comment]
I should have merged it correctly with no errors. Just to be sure I'll test it when I get home because at the moment I'm at school and I wrote it from my laptop

**Comment by S4pphiree** [comment]
I can confirm it can work without any problems! Tested every function, I had to only fix a little thing about the labels

**Comment by GhostLegionRP** [comment]
Awesome and works great! 💙

**Review by GhostLegionRP — APPROVED** [review]

**Comment by TonybynMp4** [comment]
i think this can be closed now ?

**Review by jeann2013 — APPROVED** [review]

**Comment by MalpaRP** [comment]
image


can't not open inventory

**Comment by S4pphiree** [comment]
> image
> 
> can't not open inventory

A lot of things changed with the inventory since I made this PR, I've basically stopped supporting everything I made because of not enough time, consider this PR obsolete

**Comment by MalpaRP** [comment]
> image
> 
> can't not open inventory

Well, unfortunately ... Thank you for your quick reply.

**Comment by S4pphiree** [comment]
> > image
> > can't not open inventory
> 
> Well, unfortunately ... Thank you for your quick reply.

I know, I tried pushing it but with no conclusion, consider this is the V2, maybe, when I'll have enough time I'll make a V3!

**Pull request closed without merging**
