### PR TITLE
Fixed item disappear when swapping unique items

### PR DESCRIPTION
**Pull request by HarithMichael**
Fixed item swapping, When swapping unique item it makes the item disappear

Example how to reproduce the problem: https://streamable.com/5945fe

### CODE REVIEW

**Comment by Z3rio** [comment]
Hm, I see no issues with the actual code except for it being outdated, so if you could merge it / update it through the buttons provided by github then that would be great.
I would have to test it myself when I get home though before approving it fully.

**Comment by nzkfc** [comment]
This needs an update.

**Comment by XD777OP** [comment]
This Really Fixes The Disappearing issue in My Server.

**Review by XD777OP — APPROVED** [review]

**Comment by nzkfc** [comment]
> This Really Fixes The Disappearing issue in My Server.
I tried it 2 times just in case and once on my latest version of qb scripts and it works, but you couldn't stack non unique items.

**Comment by CptNoHand** [comment]
Confirm, when you run this code, you can't stack non unique items anymore..

**Comment by nzkfc** [comment]
Knew it haha...

**Comment by nzkfc** [comment]
This has been resolved now and this can be closed.

**Comment by tom-osborne** [comment]
Issue fixed in #376

**Pull request closed without merging**
