### PR TITLE
add draw weapon event

### PR DESCRIPTION
**Pull request by KamuiKody**
## Description

adds a trigger event prior to setting the weapon that defines the weapon and triggers the draw weapon loop then when you put the weapon away it breaks it

## Checklist

- [ x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [ x] My code fits the style guidelines.
- [ x] My PR fits the contribution guidelines.

### CODE REVIEW

**Review by r0adra93 — APPROVED** [review]
No errors received
clean
as they say in trucking RUN IT!

**Comment by r0adra93** [comment]
Merge the main branch into this and I will rereview the code and approve it again!

**Review by Irishstevie — APPROVED** [review]
I have been running this for a month and installed it on a few new copy of the core
Its all good to go and is needed for qb-smallresources

**Review by Z3rio — APPROVED** [review]
LGTM

**Comment by zwkf** [comment]
image

**Pull request merged**
