### PR TITLE
Vehicle trunk code cleanup, and per car vehicle trunk slots and weight

### PR DESCRIPTION
**Pull request by PatalJunior**

### CODE REVIEW

**Comment by GhzGarage** [comment]
There’s a typo in there “Bcore” and also get display name is unreliable because it limits amounts of characters to like 7

**Comment by PatalJunior** [comment]
> There’s a typo in there “Bcore” and also get display name is unreliable because it limits amounts of characters to like 7

Would there be any alternative to the get display name

The typo I noticed, but I'm noob with git and i'll fix it and send other one just figuring it out

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-core/blob/f28f64fe68be08e75c5e8d161382b8c8db553901/shared/vehicles.lua#L4587

**Comment by mickeygeecom** [comment]
@PatalJunior you can use GetEntityArchetypeName(veh)
- works both client and server and supports "custom" vehicles

**Pull request closed without merging**
