### PR TITLE
Moving JQuery to Vue.JS 3

### PR DESCRIPTION
**Pull request by restray**
Hello everyone 👋 !

Like I said on the main Discord, I'll try to convert the JQuery file (who is actually a non-readable file with way too much lines and functions without docs.)

My goal is to make this gigantesque JavaScript file, a more readable, understandable and easy-to-work on. I'll document every part of the project and I will be 100% ready to answer any question or critic!

(If you're working on a similar feature, tell me ASAP so I don't waste time on useless lines of codes !)

# ❔ Why

I'll explain why I decided to try a pull request on this project:
 - Huge file, that i'll split into vuejs files compiled by yarn and webpack (FiveM Native)
 - compiled code to avoid any little hacker to just open NUI and type some JS commands lol (*clearly not an argument btw*)
 - VueJS3: Used on QBCore, FiveM-Chat and a easy-to-learn/easy-to-use JS Framework (*and my favorite one*)
 - Avoid any `setHTML` with JQuery (that makes things scary as hell)
 
The points that I'll take care of:
 - Mojito (Discord member) told me to be carefull about **DnD libraries** (that could cause troubles on FiveM)
 - Documentation: I'll try to comment every weird part and the whole **communication between every components**
 - The interface will stay (as possible) as it is now. (*So no need to learn or document a new design!*)
 - Allow Translations on the menu (*I'm French, and some of my friends are just struggling with certain parts*)

### About the Drag And Drop (most difficult part of the pull request)

FiveM disabled all kind of build-in drag-n-drop events on JavaScript in NUI. So I need to build a new one from scratch (*I really don't like JQuery lol*)

This part of the code is currently horrible but will be refractored at the end to be clear, simple (as possible) and well formatted

# 🎯 Target

I need to complete this ToDo, feel free to comment so I can add things in it!

- [x] Add compilation with yarn and webpack
- [x] Add default components
   - [x] `App`: The entrypoint of the project, it'll manage both keyboard and message events
      - [x] `RobPlayer`
   - [x] `Inventory`: represents the Tab Menu
      - [x] `ItemInfo`: will show the information of hovered item
      - [x] `PlayerInventory`: The left part of the inventory
      - [x] `OtherInventory`: The right part of the inventory
      - [x] `Actions`: The actions buttons (when drop on) in the middle of the inventory
      - [x] Inventory Types:
         - [x] `player`
         - [x] `stash`
         - [x] `trunk`
         - [x] `glovebox`
         - [x] `shop`
         - [x] `traphouse`
         - [x] `crafting`
         - [x] `attachment_crafting`
         - [x] `otherplayer`
      - [x] `Weights`: For both Player and other inventory (calculated automatically)
      - [x] `Progress Bar Weight`: [Related to this ticket](https://github.com/qbcore-framework/qb-inventory/pull/169)
   - [x] `Hotbar`: the Hotbar of the player
   - [x] `ItemBox`: When an item of the user is removed, added or used
   - [x] `RequiredItems`: When an item is required for a specific action (tested with bankrobbery)
   - [x] `Items`: Represent a drag-n-droppable element in the menu
      - [x] `Weapon`: Represent a weapon with serial number, loaded ammos and weapon status
      - [x] `RegularItem`: Represent a regular item
      - [x] `Attachments`: Represent Attachments to weapon (maybe when drag, highlight the weapons who can take it)
      - [x] `Combinable`: Let the user mix two items (by dropping one on other)
      - [x] `Support DnD`
   - [x] `WeaponAttachments`: Represent the middle click menu on weapon to setup attachments
 - [x] Add Default VueJS Bus Events
    - [x] Add DnD event when an item is dragged somewhere (update the inventories)
       - [x] on not droppable zone
       - [x] on empty slot
       - [x] on same item type (stackable)
       - [x] on same item type (non stackable)
       - [x] `Give` Drop zone
       - [x] `Use` Drop zone
    - [x] Add a notfications alerts event (popup item to tell the user something is wrong)
  - [x] Add Translation support (from Lua file could be a non negligible bonus)
 
# 💬 Reviews/Comments

If you want to discuss my around choice on Vue.JS 3, I'll answer your questions with pleasure. If you're curious or wanna contribute with me, feel free to send me a DM on Discord (Restray#0007)!

If you want to review my script, show me an error, or discuss a workaround: feel free to open a review! I'll check it ASAP.

# ⏲️ Estimated Time

I'll try to work as much as possible on it, but I'm not certain to finish it before 2 weeks minimum.

# ☁️ What this migration means ?

What this migration says out loud:
 - An easier way to debug (major components are separated and the most complicated parts are commented)
 - it allows a better development process (by compartmentalizing and dispatch every functions: one component: one usage.)

What does that mean to me:
 - Be able to see the cash in the inventory (and maybe even setup a slot only for it to let players exchange money easily)
 - Add CSS examples/designs that could be easily changeable.
 - Let non developer contribute by creating the translations files (even for JS part)
 - Show nearest players to give item
 - Let admin access player inventory and interact with it pretty easily!

And the negative part of it:
 - Complete the README.md with the common issues players can face (like `webpack` and `yarn` compilation) and Linux "how to build the script"
 - Add the `Github Feature/Git tag` to include a build in the resource (so server creators don't struggle on installation) *pretty much easy to do with Github Action NPM bot !*

### CODE REVIEW

**Comment by restray** [comment]
For those who are actually curious about my progression:
 - I found a way to use DragNDrop, from my latest commit. Not finished. I Need to add droppable zone.
 - I'll try to documents this mess i've done tonight

What you can currently do:
 - Use you HotBar in game
 - You can open your inventory and move things around (the item drag is just a demo for the work who still need to be done)
 - View (as a notification) the items you are using or the items removed/added
 
That's all for me, feel free to comment over here or discuss with me on Discord!

**Comment by KingRyuShin** [comment]
don't forget item quality (duration) like a little css bar under the image in inventory.

**Comment by restray** [comment]
It's already done and it' working :)

**Comment by evanillaa** [comment]
follow

**Comment by restray** [comment]
__For the news of the days__:
Pretty much *every* (without weapon attachment and combining items) inventory works.

My approach on the calculation on item drops in the inventory is completly different and the cursor change whether you're on a "droppable zone" or a "non droppable zone"

The ToDo list is up-to-date and you can try the resource from my repository on my branch!

**Comment by KingRyuShin** [comment]
Nice, you did a great job.

-------

I've verified the quality system you added. It will only work for weapon. You should add an option so we can set it on normal item too.
And there are some items that have a definite amount of "uses" before it get destroyed, should also add it into the quality label like so : 

```
if (newData.info.quality < 25 || newData.info.uses == 1) {
                            QualityColor = "rgb(192, 57, 43)";
                        } else if (newData.info.quality > 25 && newData.info.quality < 50 || newData.info.uses == 2) {
                            QualityColor = "rgb(230, 126, 34)";
                        } else if (newData.info.quality >= 50 || newData.info.uses == 2) {
                            QualityColor = "rgb(15, 255, 213)";
                        }
```

Gotta do it for all the info.quality though.

**Comment by KingRyuShin** [comment]
If I could make a suggestion.

would it be possible for you to add cash displayed in the inventory as an item ? I know some like it and some don’t, so having a toggle in the config for it could also be nice.

**Comment by restray** [comment]
> If I could make a suggestion.
> 
> would it be possible for you to add cash displayed in the inventory as an item ? I know some like it and some don’t, so having a toggle in the config for it could also be nice.

I finish this pull request then I'll do another one to add it!

**Comment by evanillaa** [comment]
hi bro can add
1. See cash in inventory 
2. add anim when close inv
3. dont forget  jerry can healthbar
4. fix label size item
5. https://github.com/qbcore-framework/qb-inventory/pull/169

**Comment by KingRyuShin** [comment]
Animation should only be done when giving or dropping an item, otherwise I find it stupid unless if you have 1 item on you and it give you a bag automaticly and then do an animation to search the bag.

**Comment by restray** [comment]
Progress bar added: 
image

**Comment by restray** [comment]
I've almost finished everything, I'm actually a little bit proud of the result! It misses 2 functionnalities: notification on error and rob player.

After that I can let you handle this pull request!

**Comment by KingRyuShin** [comment]
> I've almost finished everything, I'm actually a little bit proud of the result! It misses 2 functionnalities: notification on error and rob player.
> 
> I can't test the "other player inventory" feature, that's why set the task on "done" even if it's not tested!
> 
> After that I can let you handle this pull request!

Nice work man, can't wait to test the final result !
Question, on the "give" option, does it actually give to the closest person or it's a prompt and you enter the playerid (which is better in my opinion)

**Comment by restray** [comment]
> Question, on the "give" option, does it actually give to the closest person or it's a prompt and you enter the playerid (which is better in my opinion)

I reproduce the precedent behaviour, the other method could be an option for sure (but be more complexe)

I'll push it like it is right now, i'll do pull request later for this

**Comment by restray** [comment]
Will resolve: https://github.com/qbcore-framework/qb-inventory/issues/248 and https://github.com/qbcore-framework/qb-inventory/issues/244

**Comment by restray** [comment]
(The last commit was an idea of @KingRyuShin)

**Comment by restray** [comment]
> How should I do it ? (2 possibilities: add "..." at the end when the label is too long, or shrink the label)
The last commit patch the issue with longs items labels. It cut when the length of the label is > that 10 and add "..." (when the player hover the name, it should see the label item)

**Comment by evanillaa** [comment]
Put in the boxes from 1 TO 6
and test press Z
not show all boxes

**Comment by restray** [comment]
> Put in the boxes from 1 TO 6 and test press Z not show all boxes

Patched in the commit above

**Comment by evanillaa** [comment]
Is it possible to add a new feature by right-clicking the mouse?
With it, I can transfer the entire content of a cell to another cell
The advantage is that it transfers the entire content of the cell and not one or two elements

**Comment by istesoruisteboru** [comment]
> Is it possible to add a new feature by right-clicking the mouse? With it, I can transfer the entire content of a cell to another cell The advantage is that it transfers the entire content of the cell and not one or two elements

plus.
maybe middle buttons {give drop use) merge with that right click :)
imagine right click to item little box opens with inputb + use + give + drop button.

pros clean look.

**Comment by restray** [comment]
> Is it possible to add a new feature by right-clicking the mouse? With it, I can transfer the entire content of a cell to another cell The advantage is that it transfers the entire content of the cell and not one or two elements

I'll do it ASAP !

**Comment by restray** [comment]
> > Is it possible to add a new feature by right-clicking the mouse? With it, I can transfer the entire content of a cell to another cell The advantage is that it transfers the entire content of the cell and not one or two elements
> 
> plus. maybe middle buttons {give drop use) merge with that right click :) imagine right click to item little box opens with inputb + use + give + drop button.
> 
> pros clean look.

Changing the design (UI/UX) were not the main goal of the issue, I wait for this PR to be treated by the core team then I'll think about doing another PR or you can do it if you like it though

**Comment by DannysRP** [comment]
I did attempt to use your version of inventory with all these changes but couldn't get it to work.

**Comment by restray** [comment]
> I did attempt to use your version of inventory with all these changes but couldn't get it to work.

Errors ? Behaviours of the server and the client ?
You should give more informations so I can patch the bugs... Your message doesn't help a lot...

**Comment by DannysRP** [comment]
No errors from what I've seen. I am just testing your PR so I downloaded your version to do so. Nothing in the F8 or console. Opening the inventory shows your cursor but the inventory does not load. Just me personally

**Comment by restray** [comment]
> No errors from what I've seen. I am just testing your PR so I downloaded your version to do so. Nothing in the F8 or console. Opening the inventory shows your cursor but the inventory does not load. Just me personally

I need few more informations:
 - Do you have a "html" and "html_app" folder in the resource?
 - The server is running on Linux or Windows?
 - Do you have "node" and "yarn" installed on your computer?
 - Are you sure you've download the latest version, using git (on branch restray_refracto_js) or zipfile (https://github.com/restray/qb-inventory/archive/refs/heads/restray_refracto_js.zip) ? (If you're not sure, try again and restart your server)
 - Are the "yarn" and "webpack" resources enable on your server?

I'l wait for your answer :)

**Comment by restray** [comment]
> No errors from what I've seen. I am just testing your PR so I downloaded your version to do so. Nothing in the F8 or console. Opening the inventory shows your cursor but the inventory does not load. Just me personally

After many messages, the matter comes from the script that wasn't updated (I do a lot of updates, that is maybe the initial issue lol)

**Comment by DannysRP** [comment]
Yeah yeah all good now!

**Comment by xenfovn** [comment]
i can see current weight inventory ?

**Comment by restray** [comment]
> i can see current weight inventory ?

Yes, absolutely, it's real time calculated!

**Comment by restray** [comment]
I used a more understandable way to inform the user of the inventory weight

Look at the progress bar on top of both inventories.

**Comment by xenfovn** [comment]
https://streamable.com/lalf12

this is a bug ?

**Comment by restray** [comment]
Can you open issues instead of complaining in a closed PR ?
That would be easier to manage!
(And yes, this is a bug, show me your F8)

**Pull request merged**
