### PR TITLE
Fix weapon dont lost quality and ammo

### PR DESCRIPTION
**Pull request by Pbtm999**
Fix weapon dont lost quality and ammo

Fix glitch when you change a item by an weapon on inventory the weapon dont lose quality and ammo.

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by Branqueador** [comment]
works as intended, thanks very much

**Comment by i-kulgu** [comment]
> works as intended, thanks very much

How did you tested it ? Can you explain so i can test it too ?

**Review by Branqueador — APPROVED** [review]

**Comment by Branqueador** [comment]
@i-kulgu https://streamable.com/bwj7ah this way video is not mine btw

**Comment by i-kulgu** [comment]
> @i-kulgu https://streamable.com/bwj7ah this way video is not mine btw

That video has nothing to do with the PR.
PR is for : "Fix glitch when you change a item by an weapon on inventory the weapon dont lose quality and ammo."

**Comment by Branqueador** [comment]
> > @i-kulgu https://streamable.com/bwj7ah this way video is not mine btw
> 
> That video has nothing to do with the PR. PR is for : "Fix glitch when you change a item by an weapon on inventory the weapon dont lose quality and ammo."

My bad sorry! before you could replace an item (without quality) for the weapon like that weapon would not loose quality.
now with this PR weapon will be removed from you'r hand when moved to another slot

**Comment by Edvo1901** [comment]
What is `inventory:sever:UpdateWeapon`? There is no such an event

**Pull request closed without merging**
