### PR TITLE
Move item not exist text to locale

### PR DESCRIPTION
**Pull request by woerki**
Fixed the replace of locale instead of english text.

### CODE REVIEW

**Review by i-kulgu — APPROVED** [review]
LGTM!

**Comment by zwkf** [comment]
A translation does not appear to exist with this key

**Review by zwkf — CHANGES_REQUESTED** [review]
A translation does not appear to exist with this key

**Comment by woerki** [comment]
@zwkf 
I made a few requests and all are together; only GitHub doesn't want to merge it in one big request. Sorry, but so it is a little bit curiously to understand.
My intention was to delete the english notify texts and replace them with language variables.

**Comment by i-kulgu** [comment]
> A translation does not appear to exist with this key

The translation is just there inside en.lua : 19

**Review by zwkf — APPROVED** [review]
LGTM

**Comment by woerki** [comment]
@zwkf 
When you show [here](https://github.com/qbcore-framework/qb-inventory/pulls?q=is%3Apr+author%3Awoerki+is%3Aclosed) you can see that there had been more translation fixes.
I don't know how to combine the requests in one big request, so it had been closed without any improvements/combinations.

**Pull request merged**
