### PR TITLE
fix: amount is nil in `GetTotalWeight` + misc lint issues

### PR DESCRIPTION
**Pull request by Z3rio**
## Description
Upon running `/giveitem 1 radio 1`, you'll run into the following error.
image
(First print is raw item json, second print is weight & amount)

Perhaps this should be looked into more deeply, as the amount value should be defined here.
Aswell as the fact that this error might be happening at other places

Perhaps, this is caused by the radio being a unique item?

## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by Z3rio** [comment]
That last nil value in the lint report is fixed by my other PR.

**Comment by ChristianBDev** [comment]
I have personally tried this and cannot replicate the issue, how recent is all your qb files? If up to date is there any errors before this?

**Comment by Z3rio** [comment]
> I have personally tried this and cannot replicate the issue, how recent is all your qb files? If up to date is there any errors before this?

Ran a completely fresh install a couple minutes before this.

**Comment by Z3rio** [comment]
Perhaps this issue was caused by going from the old inventory and such, to the new inventory.
Nevertheless, its an issue that did occur for me, under normal usage circumstances

**Comment by Z3rio** [comment]
> This PR has had 60 days of inactivity & will close within 7 days

y'all are the ones inactive, not me

**Comment by GhzGarage** [comment]
I'll check it out, i've never ran across this issue before and i use that command 100's time a day lol

**Comment by Z3rio** [comment]
> I'll check it out, i've never ran across this issue before and i use that command 100's time a day lol

Fair enough, I do realize now in after-hand that this might've just been an one off issue.
And in that case, I could remove the `GetTotalWeight` changes, and just leave you with the lint fixes, if thats of interest?

Although, these changes should cause no harm, if anything, just good.

**Pull request merged**
